/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p ofonomodemconnectionmanager.h -c OfonoModemConnectionManager ofonomodem.xml org.ofono.ConnectionManager
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OFONOMODEMCONNECTIONMANAGER_H_1417421649
#define OFONOMODEMCONNECTIONMANAGER_H_1417421649

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

#include "qdbusdatatypes.h"

/*
 * Proxy class for interface org.ofono.ConnectionManager
 */
class OfonoModemConnectionManager: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.ConnectionManager"; }

public:
    OfonoModemConnectionManager(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OfonoModemConnectionManager();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QDBusObjectPath> AddContext(const QString &type)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(type);
        return asyncCallWithArgumentList(QLatin1String("AddContext"), argumentList);
    }

    inline QDBusPendingReply<> DeactivateAll()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("DeactivateAll"), argumentList);
    }

    inline QDBusPendingReply<OfonoObjectPropertyList> GetContexts()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetContexts"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> GetProperties()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetProperties"), argumentList);
    }

    inline QDBusPendingReply<> RemoveContext(const QDBusObjectPath &path)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(path);
        return asyncCallWithArgumentList(QLatin1String("RemoveContext"), argumentList);
    }

    inline QDBusPendingReply<> SetProperty(const QString &property, const QDBusVariant &value)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(property) << QVariant::fromValue(value);
        return asyncCallWithArgumentList(QLatin1String("SetProperty"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void ContextAdded(const QDBusObjectPath &path, const QDBusVariant &properties);
    void ContextRemoved(const QDBusObjectPath &path);
    void PropertyChanged(const QString &name, const QDBusVariant &value);
};

#endif
